#!/usr/bin/env bash
# =============================================================================
# generate_changelog.sh
# Auto-generate a structured CHANGELOG.md from git history
# Bounty: $50 — Claude Builders Bounty #1
# Usage: bash generate_changelog.sh [output_file]
# =============================================================================

set -euo pipefail

OUTPUT="${1:-CHANGELOG.md}"
REPO_DIR="${2:-.}"

cd "$REPO_DIR"

# Check if we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "❌ Error: Not in a git repository."
  echo "Usage: bash generate_changelog.sh [output_file] [repo_path]"
  exit 1
fi

echo "🔍 Generating CHANGELOG from git history..."

# Get the last tag (fall back to first commit if no tags)
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
SINCE_REF="${LAST_TAG:-$(git rev-list --max-parents=0 HEAD)}"

echo "   Last tag: ${LAST_TAG:-'(no tags - using initial commit)'}"

# Get commits since last tag
COMMITS=$(git log "$SINCE_REF..HEAD" --pretty=format:"%H|%s|%an|%ad" --date=short 2>/dev/null || git log --pretty=format:"%H|%s|%an|%ad" --date=short HEAD)

if [ -z "$COMMITS" ]; then
  echo "⚠️  No new commits found since $SINCE_REF."
  echo "   Generating from all commits instead..."
  COMMITS=$(git log --pretty=format:"%H|%s|%an|%ad" --date=short HEAD)
fi

# Count commits
COMMIT_COUNT=$(echo "$COMMITS" | grep -c . || true)
echo "   Found $COMMIT_COUNT commit(s) since ${SINCE_REF:-beginning}"

# Categorize commits
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""
OTHER=""

while IFS='|' read -r HASH MESSAGE AUTHOR DATE; do
  [ -z "$MESSAGE" ] && continue
  
  CATEGORY="other"
  CLEAN_MSG=$(echo "$MESSAGE" | sed 's/^[^a-zA-Z]*//')
  MSG_LOWER=$(echo "$CLEAN_MSG" | tr '[:upper:]' '[:lower:]')
  
  # Try conventional commits format first (feat:, fix:, etc.)
  if echo "$CLEAN_MSG" | grep -qE '^feat(\([^)]+\))?:' ; then
    CATEGORY="added"
  elif echo "$CLEAN_MSG" | grep -qE '^fix(\([^)]+\))?:' ; then
    CATEGORY="fixed"
  elif echo "$CLEAN_MSG" | grep -qE '^(chore|refactor|perf)(\([^)]+\))?:' ; then
    CATEGORY="changed"
  elif echo "$CLEAN_MSG" | grep -qE '^(docs|style)(\([^)]+\))?:' ; then
    CATEGORY="changed"
  elif echo "$CLEAN_MSG" | grep -qE '^(revert|remove)(\([^)]+\))?:' ; then
    CATEGORY="removed"
  # Semantic prefix matching
  elif echo "$MSG_LOWER" | grep -qE '^(feat|feature|add|new|implement|create|introduce)'; then
    CATEGORY="added"
  elif echo "$MSG_LOWER" | grep -qE '^(fix|bugfix|bug|hotfix|patch|resolve|correct)'; then
    CATEGORY="fixed"
  elif echo "$MSG_LOWER" | grep -qE '^(change|update|refactor|improve|modify|upgrade|migrate|redesign)'; then
    CATEGORY="changed"
  elif echo "$MSG_LOWER" | grep -qE '^(remove|delete|drop|deprecate|cleanup)'; then
    CATEGORY="removed"
  fi

  SHORT_HASH=$(echo "$HASH" | cut -c1-7)
  ENTRY="- ${MESSAGE%%.*}. ([${SHORT_HASH}](https://github.com/$(git remote get-url origin 2>/dev/null | sed 's/.*:\(.*\)\.git/\1/' || echo 'repo')/commit/${HASH}))"
  
  case "$CATEGORY" in
    added)   ADDED="${ADDED}\n${ENTRY}" ;;
    fixed)   FIXED="${FIXED}\n${ENTRY}" ;;
    changed) CHANGED="${CHANGED}\n${ENTRY}" ;;
    removed) REMOVED="${REMOVED}\n${ENTRY}" ;;
    *)       OTHER="${OTHER}\n${ENTRY}" ;;
  esac
done <<< "$COMMITS"

# Generate the CHANGELOG
{
  echo "# Changelog"
  echo ""
  echo "## [Unreleased]"
  echo ""
  echo "> Generated on $(date '+%Y-%m-%d') from commit history."
  echo "> Auto-categorized by [generate_changelog.sh](generate_changelog.sh)"
  echo ""
  echo "---"
  echo ""

  # Get current version
  CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
  echo "**Since:** \`${SINCE_REF}\` → **Current:** \`$(git rev-parse --short HEAD)\`"
  echo "**Latest tag:** \`${CURRENT_TAG}\`"
  echo ""

  if [ -n "$ADDED" ]; then
    echo "### ✨ Added"
    echo -e "$ADDED" | grep -v '^$'
    echo ""
  fi

  if [ -n "$FIXED" ]; then
    echo "### 🐛 Fixed"
    echo -e "$FIXED" | grep -v '^$'
    echo ""
  fi

  if [ -n "$CHANGED" ]; then
    echo "### 🔄 Changed"
    echo -e "$CHANGED" | grep -v '^$'
    echo ""
  fi

  if [ -n "$REMOVED" ]; then
    echo "### 🗑️ Removed"
    echo -e "$REMOVED" | grep -v '^$'
    echo ""
  fi

  if [ -n "$OTHER" ]; then
    echo "### 📦 Other"
    echo -e "$OTHER" | grep -v '^$'
    echo ""
  fi

  echo "---"
  echo "_Generated by [Claude Builders Bounty #1](https://github.com/claude-builders-bounty/claude-builders-bounty/issues/1)_"
} > "$OUTPUT"

echo "✅ CHANGELOG generated → $OUTPUT"
echo ""
echo "📋 Summary:"
echo "   ✨ Added:    $(echo -e "$ADDED" | grep -c . || echo 0)"
echo "   🐛 Fixed:   $(echo -e "$FIXED" | grep -c . || echo 0)"
echo "   🔄 Changed: $(echo -e "$CHANGED" | grep -c . || echo 0)"
echo "   🗑️ Removed:  $(echo -e "$REMOVED" | grep -c . || echo 0)"
echo "   📦 Other:   $(echo -e "$OTHER" | grep -c . || echo 0)"
